version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
      - echo "Zipping the Lambda function"
      - zip -r lambda_function.zip .

  post_build:
    commands:
      - echo "Deploying to AWS Lambda"
      - aws lambda update-function-code --function-name lambda-cicd --zip-file fileb://lambda_function.zip

artifacts:
  files:
    - lambda_function.zip
